```{r}
Ironbard_cities=c("Vardo", "Hofn", "Helvig", "Bjurholm", "Blonduos", "Helluland")

Providence_cities=c("Hayarano", "Shinobi", "Biruwa", "Takazaki", "Akkeshi", "Kiyobico", "Reading", 
                    "Nelson", "Arcadia")

Bonne_Sante_cities=c("Nidoma", "Talu", "Riroua", "Pauma", "Valais", "Gordes", "Maeva", "Kinsale", 
                     "Colmar", "Vaiku", "Mahuti", "Eden")

set.seed(288)
srs_Ironbard_cities=sample(Ironbard_cities, 3)
srs_Providence_cities=sample(Providence_cities, 3)
srs_Bonne_Sante_cities=sample(Bonne_Sante_cities, 3)

sampled_cities=c(srs_Ironbard_cities, srs_Providence_cities, srs_Bonne_Sante_cities)

print(sampled_cities)
birth_records <- read.csv("birth_records.csv")

# we now have 3 cities from each island stored in variable sampled_cities. Time to take an SRS 
# of people who are 66 or older from each city's birth records.

Blonduos_birth_records=birth_records$Blonduos[1:108]

Blonduos_sample_11=sample(Blonduos_birth_records, 11)
# manually checking how many of these people are alive, and if they are alive, if they consent
# to participate in the study.

# Hannah Jensen: alive and consents! X
# Sakura Collins: alive but declined
# Sven Blomgren: deceased
# Elena Blomgren: alive and consented! X
# Dean Price: ailve and consented. X
# Ashley Brown, alive and consented X
# Olson Solber: deceased
# Ian Sato: deceased
# Maximilian Solberg: alive but declined.
# Brenda Sorenson: alive and consented X
# Emma McCarthy: deceased.

# obtained 5/11 participants. Need to re-sample 6 more people.
# removing the previous 11 values from the vector:

elements_to_remove=c("22/300 Hannah Jensen", "11/309 Sakura Collins", "13/303 Sven Blomgren",
  "19/302 Elena Blomgren", "03/306 Dean Price", "04/307 Ashley Brown", "12/300 Olson Solberg",
  "14/309 Ian Sato", "22/308 Maximilian Solberg", "13/301 Brenda Sorensen", 
  "13/306 Emma McCarthy")

Blonduos_birth_records <- Blonduos_birth_records[!(Blonduos_birth_records %in% elements_to_remove)]

Blonduos_sample_24=sample(Blonduos_birth_records, 24)
#print(Blonduos_sample_24)

# Gunnar Solberg: deceased
# Sian Morris: alive and consented (6/11)
# Jana Bager: consented (7/11)
# Agda Bager: deceased 
# Misaki Price: deceased
# Kaito Sato: deceased
# Pierrick Solberg: deceased
# Ella Solberg: declined consent
# Axel Sorensen: consented (8/11)
# Christian Sorensen: deceased
# Dane Carlsen: deceased
# Jonas Sorensen: consented (9/11)
# Christopher Lenz: deceased
# Leira Carlsen: deceased
# Matthias Solberg: deceased
# Tyr Solberg: declined consent
# Jessica Morris: deceased
# Lucia Ibsen: deceased
# Anastasia Ibsen: consented (10/11)
# Michelle Price: declined consent
# Jamie Morris: deceased
# Tate Yamada: deceased
# Megan Sato: deceased
# Ragnar Carlsen: consented. (11/11)
Blonduos_sample = c(
"Hannah Jensen",
"Elena Blomgren",
"Dean Price",
"Ashley Brown",
"Brenda Sorensen",
"Sian Morris",
"Jana Bager",
"Axel Sorensen",
"Jonas Sorensen",
"Anastasia Ibsen",
"Ragnar Carlsen"
)

Vardo_birth_records = birth_records$Vardo[1:176]

Vardo_sample_29=sample(Vardo_birth_records, 29)

# print(Vardo_sample_29)

# Sian Wilson: declined
# Christopher Froehlich: consented (1/11)
# Manan Mardia: consented (2/11)
# Harold Jensen: deceased
# Lucia Solberg: consented (3/11)
# Sophia Blomgren: consented (4/11)
# Martina Lindner: deceased
# Tove Pallesen: consented (5/11)
# Per Peters: consented (6/11)
# Lucy Collins: deceased
# Emma Connolly: consented (7/11)
# Tomas Carlsen: deceased
# Sascha Guenther: deceased
# Arvid Eklund: consented (8/11)
# Sten Solberg: deceased
# Karen Madsen: deceased
# Conor Connelly: consented (9/11)
# Raphael Sorensen: deceased
# Siobhan Collins: deceased
# Jessica McCarthy: deceased
# Grace Price: consented (10/11)
# Sophia Carlsen: deceased
# Sigrid Blomgren: deceased
# David Eklund: deceased
# Riko Jackson: deceased
# Ella Medsen: deceased
# James Brown: declined
# Natalia Guenther: deceased
# Vanessa Eklund: consented!

Vardo_sample <- c(
  "Christopher Froehlich",
  "Mana Mardia",
  "Lucia Solberg",
  "Sophia Blomgren",
  "Tove Pallesen",
  "Per Peters",
  "Emma Connolly",
  "Arvid Eklund",
  "Conor Connelly",
  "Grace Price",
  "Vanessa Eklund"
)
```

```{r}
set.seed(288)
Helvig_birth_records=birth_records$Helvig[1:164]
sample(Ironbard_cities, 3) #redundant sampling for github issue
sample(Providence_cities, 3)
sample(Bonne_Sante_cities, 3)
Helvig_sample_11=sample(Helvig_birth_records, 11)
# print(Helvig_sample_11)
#"17/300 Nanami Collins" Declined   
#"27/301 Asuka Brown"      
#"19/304 Karsten Hartmann"
#"16/305 Shiori Wilson"    
#"17/301 Lynnea Ibsen" Consented    
#"28/302 Naoki Edwards"  
#"11/303 Miki Moore"       
#"21/306 Lucy McCarthy"    
#"25/303 Cariel Solberg" Consented  
#"15/303 Nils Carlsen"     
#"23/309 Anund Olsen"

#2/11

elements_to_remove <- c("17/300 Nanami Collins", "27/301 Asuka Brown", "19/304 Karsten Hartmann", "16/305 Shiori Wilson", "17/301 Lynnea Ibsen", "28/302 Naoki Edwards", "11/303 Miki Moore", "21/306 Lucy McCarthy", "25/303 Cariel Solberg", "15/303 Nils Carlsen", "23/309 Anund Olsen")

Helvig_birth_records <- Helvig_birth_records[!(Helvig_birth_records %in% elements_to_remove)]

Helvig_sample_24 <- sample(Helvig_birth_records, 31)
print(Helvig_sample_24)
#"28/310 Rita Voigt" Consented
# Arvid Solberg Consented
# Kevin Edwards Consented
# Raum Carlsen Consented
# Olina Sorensen Consented
# Pernille Carlsen consented
# Gerald Reinhardt Consented
# Katarina Lenz Consented
# Signe Sorensen Consented
#11/11

#Final Helvig Sample
#"17/301 Lynnea Ibsen"
#"25/303 Cariel Solberg"
#"28/310 Rita Voigt" Consented
# 04/304 Arvid Solberg Consented
# 17/309 Kevin Edwards Consented
# 14/310 Raum Carlsen Consented
# 18/301 Olina Sorensen Consented
# 15/304 Pernille Carlsen consented
# 13/304 Gerald Reinhardt Consented
# 24/309 Katarina Lenz Consented
# 13/305 Signe Sorensen consented.

Helvig_sample <- c(
  "Lynnea Ibsen",
  "Cariel Solberg",
  "Rita Voigt",
  "Arvid Solberg",
  "Kevin Edwards",
  "Raum Carlsen",
  "Olina Sorensen",
  "Pernille Carlsen",
  "Gerald Reinhardt",
  "Katarina Lenz",
  "Signe Sorensen")
```

```{r}
set.seed(288)
Biruwa_birth_records=birth_records$Biruwa[1:118]
sample(Ironbard_cities, 3) #Redundant sampling to fix a weird error!!
sample(Providence_cities, 3)
sample(Bonne_Sante_cities, 3)
Biruwa_sample_11=sample(Biruwa_birth_records, 11)
# print(Biruwa_sample_11)

# Liliane Gautier
# Torvald Carlsen
# Ryan Kimura

#3/11

elements_to_remove=c("22/300 Gunnar Sorensen", "14/311 Tyra Blomgren", "24/308 Liliane Gautier", "18/309 Max Leger", "24/309 Torvald Carlsen", "23/302 Ole Bager", "16/300 Ryan Kimura", "28/300 Jackson Wilson", "23/303 Chloe Collins", "01/307 Mayu Morris", "13/310 Rin Connolly")

Biruwa_birth_records <- Biruwa_birth_records[!(Biruwa_birth_records %in% elements_to_remove)]

Biruwa_sample_24=sample(Biruwa_birth_records, 35) 
print(Biruwa_sample_24)

# Sarah Bager
# Killian McCarthy
# Nanami Kimura
# Tobias Eklund
# Remy Connolly
# Cariel Blomgren
# Chanda Babu
# Sarah Solberg
#11/11

#Final Biruwa sample:
# 24/308 Liliane Gautier
# 24/309 Torvald Carlsen
# 16/300 Ryan Kimura
# 21/300 Sarah Bager
# 23/310 Killian McCarthy
# 11/306 Nanami Kimura
# 18/307 Tobias Eklund
# 04/306 Remy Connolly
# 18/305 Cariel Blomgren
# 24/308 Chanda Babu
# 24/304 Sarah Solberg

Biruwa_sample <- c("Liliane Gautier",
                  "Torvald Carlsen",
                  "Ryan Kimura",
                  "Sarah Bager",
                  "Killian McCarthy",
                  "Nanami Kimura",
                  "Tobias Eklund",
                  "Remy Connolly",
                  "Cariel Blomgren",
                  "Chanda Babu",
                  "Sarah Solberg")
```

```{r}
set.seed(288)
Shinobi_birth_records <- c(birth_records$Shinobi[1:170])
Shinobi_sample_30 <- sample(Shinobi_birth_records, 30)
#print(Shinobi_sample_30)

# 05/312 Juhani Ibsen 
# 20/315 Matthew Brown DECEASED 
# 09/306 Lena Olsen 
# 19/319 Mia Yamada
# 06/300 Elsa Thorn DECEASED
# 22/318 Ophelia Eklund DECEASED 
# 08/318 Kashvi Kumar 
# 07/301 Viggo Sorensen
# 26/300 Ava Collins 
# 14/305 Simon (Marshall) Sorensen
# 24/314 Taylor Morris DECEASED
# 06/308 Zachary Kimura DECEASED 
# 02/312 Michelle Moore DECLINED
# 01/303 Akane Watanabe
# 23/316 Shane Sato 
# 13/311 Kerstin Thorn 
# 09/319 Amy Brown DECLINED 
# 16/303 Desmond Connolly DECEASED 
# 22/318 Ophelia Eklund DECEASED 
# 11/318 Hiro Kimura DECLINED 
# 27/318 Benjamin Wilson

Shinobi_sample <- c(
  "Juhani Ibsen",
  "Lena Olsen",
  "Mia Yamada",
  "Kashvi Kumar",
  "Viggo Sorensen",
  "Ava Collins",
  "Simon (Marshall) Sorensen",
  "Akane Watanabe",
  "Shane Sato",
  "Kerstin Thorn",
  "Benjamin Wilson")

```

```{r}
Reading_birth_records <- birth_records$Reading[1:173]
set.seed(288)
Reading_sample_50 <- sample(Reading_birth_records, 50)
print(Reading_sample_50)

# 20/302 Lars Solberg
# 05/302 Derick Hughes
# 07/301 Bronwyn Wilson DECEASED 
# 19/302 Fabienne Fournier DECEASED 
# 02/301 Samuel Eklund DECLINED 
# 22/302 Adrienne Hughes DECEASED 
# 17/302 Sara Muir DECEASED 
# 19/302 Theresa Bager
# 22/301 Saika Connolly DECEASED 
# 06/302 Raphael Sorensen DECEASED 
# 09/302 Jocelyne Lacroix DECEASED 
# 11/301 Noah Morris
# 14/302 Josh Davies
# 20/302 Mia Solberg DECEASED 
# 14/302 Jeneve Solberg
# 03/302 Sarah Regan DECEASED 
# 09/301 Gretel Solberg
# 28/302 Emma Bager DECEASED 
# 01/302 Kirstie Solberg DECLINED 
# 10/301 Takahiro McCarthy DECEASED 
# 17/301 Liliane Dupuy DECEASED 
# 27/300 Raphael Solberg DECEASED 
# 24/302 Lyn Bell DECEASED 
# 24/308 Risa Nakajima DECEASED 
# 04/309 Lomash Kaur
# 18/308 Maximilian Blomgren DECLINED 
# 22/302 Adrienne Hughes DECEASED 
# 14/308 Ragnar Olsen
# 18/308 Barbara Meier DECEASED 
# 23/308 Joel Masson 
# 06/308 Sylvia Ritchie
Reading_sample <- c("Lars Solberg",
                    "Derick Hughes",
                    "Theresa Bager",
                    "Noah Morris",
                    "Josh Davies",
                    "Jeneve Solberg",
                   "Gretel Solberg",
                    "Lomash Kaur",
                    "Ragnar Olsen",
                    "Joel Masson",
                    "Sylvia Ritchie")
```

```{r}
#Bonne Sante Cities - Talu, Eden, Valais
set.seed(288)
Talu_birth_records = c(birth_records$Talu[1:220])
Talu_sample_31 <- sample(Talu_birth_records, 31) #Increased in a stepwise fashion until the correct amount is obtained
# print(Talu_sample_31)
# 16/304 Chantel Lund: DEAD
# 05/306 Saeed Laha: DEAD
# 20/309 Chahel Lingutla: DECLINED
# 19/302 Rupert Wilson: DECLINED
# 19/308 Brenda Erickson: CONSENTED (1/11)
# 04/300 Gala Eklund: DEAD
# 03/308 Gildas Gaillard: CONSENTED (2/11)
# 25/306 Nicolas Wilson: CONSENTED (3/11)
# 03/308 Charles Jensen: DEAD
# 27/300 Auguste Lund: DEAD 
# 18/300 Hailey Edwards: DECLINED
# 12/302 Sophia Watanabe: DEAD
# 13/305 Rachelle Carlsen: DEAD 
# 18/306 Sebastian Svendsen: DEAD
# 27/301 Megane Sato: CONSENTED (4/11)
# 09/303 Samuel Suzuki: DEAD
# 28/303 Erika Eklund: CONSENTED (5/11)
# 26/306 Grace Brown: DEAD
# 16/304 Magritte Herbert: CONSENTED (6/11)
# 10/304 Frederique Jensen: DEAD
# 06/308 Felix Blomgren: DEAD
# 13/301 Magritte Morris: CONSENTED (7/11)
# 20/308 King Suzuki: DEAD
# 06/308 Harvey Dupont: DEAD
# 14/310 Danielle Morel: DEAD
# 14/307 Amon Suzuki: CONSENTED (8/11)
# 26/302 Manuel Levy: DECLINED
# 23/310 Regis Lemoine: DECLINED
# 03/304 Leon Sorensen: CONSENTED (9/11)
# 20/311 Hakan Larsen: CONSENTED (10/11)
# 14/310 Rahas Babu: CONSENTED (11/11)
Talu_sample <- c("Brenda Erickson",
                 "Gildas Gaillard",
                 "Nicolas Wilson",
                 "Megane Sato",
                 "Erika Eklund",
                 "Magritte Herbert",
                 "Magritte Morris",
                 "Amon Suzuki",
                 "Leon Sorensen",
                 "Hakan Larsen",
                 "Rahas Babu")
```

```{r}
#Bonne Sante Cities - Talu, Eden, Valais
set.seed(288)
Eden_birth_records <- birth_records$Eden[1:303]
Eden_sample_42 <- sample(Eden_birth_records,42)
# print(Eden_sample_42)
# 23/304 Gabrielle (Chanha) Ramanan: CONSENTED (1/11)
# 02/308 Seymour (Nathan) Wilson: CONSENTED (2/11)
# 07/303 Fabrice Dupont: DEAD
# 10/307 Nicolas (Tom) Edwards: CONSENTED (3/11)
# 22/310 Rithul Maharaj: DEAD
# 16/306 Maalai Mardia: DEAD
# 04/306 Yuval Devar: DEAD
# 11/308 Anna Pallesen: DEAD
# 04/310 Marie Murphy: DEAD 
# 05/301 Nico Lund: DEAD
# 23/300 Beatrice Solberg: DEAD
# 20/309 Erin Morris: DEAD
# 11/302 Yvonne Petit: DEAD
# 07/302 Laasya Srinivasan: DEAD
# 12/307 Hanima Devar: CONSENTED (4/11)
# 26/306 Ryan Jackson: DEAD
# 13/308 Teala Thorn: DEAD
# 07/306 Emilie (Kaia) Chatterjee: CONSENTED (5/11)
# 09/304 Yuval Kulkarni: DEAD 
# 21/308 Kimaya Badahur: CONSENTED (6/11)
# 11/311 Keya Srinivasan: DEAD
# 18/304 Jacques Wilson: DEAD
# 20/308 Bimala Puri: DEAD
# 09/302 Elie Murphy: DEAD
# 17/311 Nihal Puri: DEAD
# 03/310 Felix Bager: DEAD
# 25/306 Brielle (Kaia) Sultana: CONSENTED (7/11)
# 06/309 Ayann Chunduri: CONSENTED (8/11)
# 04/310 Remy Bager: DEAD
# 27/303 Momoko Edwards: DEAD
# 27/303 Justin Herbert: DEAD
# 12/302 Beau Solberg: DEAD
# 12/304 Rushil Devar: DEAD
# 06/308 Shauna Jackson: DECLINED
# 04/301 Mizuki Edwards: DEAD
# 18/304 Kaia Ramanujan: CONSENTED (9/11)
# 04/303 Conor Wilson: DEAD
# 05/306 Elle Dupont: DEAD
# 04/311 Nayan Khan: CONSENTED (10/11)
# 25/307 Nabhi Datta: CONSENTED (11/11)
Eden_sample <- c("Gabrielle (Chanha) Ramanan",
                 "Seymour (Nathan) Wilson",
                 "Nicolas (Tom) Edwards",
                 "Hanima Devar",
                 "Emilie (Kaia) Chatterjee",
                 "Kimaya Badahur",
                 "Brielle (Kaia) Sultana",
                 "Ayann Chunduri",
                 "Kaia Ramanujan",
                 "Nayan Khan",
                 "Nabhi Datta")
```

```{r}
#Bonne Sante Cities - Talu, Eden, Valais
set.seed(288)
Valais_birth_records <- birth_records$Valais[1:103]
Valais_sample_45 <- sample(Valais_birth_records, 45)
# print(Valais_sample_45)
# 13/308 Melissa Wilson: DEAD
# 21/302 Viktoria Sorensen: DEAD
# 10/303 Kirstie Eklund: CONSENTED (1/11)
# 21/301 Robert Moore: DEAD
# 06/300 Emy Brown: DECLINED
# 20/300 Paige Watanabe: DEAD
# 09/300 Helga Svendsen: CONSENTED (2/11)
# 02/311 King Wilson: DEAD
# 26/300 Miho Collins: CONSENTED (3/11)
# 18/300 Patricia Edwards: DEAD
# 27/302 Renee (Ayaka) Yamada: DEAD
# 12/302 Nadege Leclerc: DEAD
# 01/305 Lauren Connolly: CONSENTED (4/11)
# 24/305 Camille (Jeneve) Bager: DECLINED 
# 10/300 Sarah Morris: DEAD
# 07/301 Mike Yamada: DECLINED
# 12/305 Akane Morris: CONSENTED (5/11)
# 01/302 Maika Solberg: DEAD
# 22/301 Finlay Brown: DEAD
# 07/301 Emma Blomgren: DEAD
# 16/303 Philipp Sorensen: DEAD
# 17/300 Isobel Brown: DEAD
# 27/303 Julien Chevallier: DEAD
# 09/304 Alicia Jones: DEAD
# 18/307 Leon Connolly: CONSENTED (6/11)
# 21/302 Matthias Sorensen: DEAD
# 02/303 Ross Connolly: DEAD
# 24/304 Rida Jensen: DECLINED
# 28/303 Nicole Solberg: DEAD
# 03/302 Sophie Hall: DEAD
# 24/305 Florence (Kaya) Bager: DECLINED
# 13/302 Percy Blomgren: DEAD
# 11/304 Ole Ibsen: CONSENTED (7/11)
# 20/303 Tristan (Juhani) Sorensen: DECLINED
# 27/302 Julie Lund: CONSENTED (8/11)
# 02/303 Aidan Brown: DECLINED
# 25/300 Sarah Brown: DEAD
# 16/301 Yujia Morris: DEAD 
# 13/306 Christele Levy: DEAD
# 19/305 Lionel Collin: DEAD
# 05/309 Holly Connolly (hell yeah): CONSENTED (9/11)
# 11/301 Agda Carlsen: CONSENTED (10/11)
# 10/302 Johanna Jensen: DEAD
# 28/301 Jakob Sorensen: DEAD
# 07/303 Juliette (Alina) Jensen: CONSENTED (11/11)
Valais_sample <- c(
  "Kirstie Eklund",
  "Helga Svensen",
  "Miho Collins",
  "Lauren Connolly",
  "Akane Morris",
  "Leon Connolly",
  "Ole Ibsen",
  "Julie Lund",
  "Holly Conolly",
  "Agda Carlsen",
  "Juliette (Alina) Jensen")

```

```{r}
set.seed(288)
all_individuals <- c(Blonduos_sample,
                     Vardo_sample,
                     Helvig_sample,
                     Biruwa_sample,
                     Shinobi_sample,
                     Reading_sample,
                     Talu_sample,
                     Eden_sample,
                     Valais_sample)
aerobic_group <- sample(all_individuals,33,replace=FALSE)
all_individuals <- all_individuals[!(all_individuals %in% aerobic_group)]
anaerobic_group <-sample(all_individuals,33,replace=FALSE)
control_group <- all_individuals[!(all_individuals %in% anaerobic_group)]

participants_random <- data.frame(aerobic_group,anaerobic_group,control_group)
write.csv(participants_random,"participant_groups.csv")

```