```{r}
Ironbard_cities=c("Vardo", "Hofn", "Helvig", "Bjurholm", "Blonduos", "Helluland")

Providence_cities=c("Hayarano", "Shinobi", "Biruwa", "Takazaki", "Akkeshi", "Kiyobico", "Reading", 
                    "Nelson", "Arcadia")

Bonne_Sante_cities=c("Nidoma", "Talu", "Riroua", "Pauma", "Valais", "Gordes", "Maeva", "Kinsale", 
                     "Colmar", "Vaiku", "Mahuti", "Eden")

set.seed(288)
srs_Ironbard_cities=sample(Ironbard_cities, 3)
srs_Providence_cities=sample(Providence_cities, 3)
srs_Bonne_Sante_cities=sample(Bonne_Sante_cities, 3)

sampled_cities=c(srs_Ironbard_cities, srs_Providence_cities, srs_Bonne_Sante_cities)

print(sampled_cities)

# we now have 3 cities from each island stored in variable sampled_cities. Time to take an SRS 
# of people who are 66 or older from each city's birth records.

Blonduos_birth_records=c(
"01/300	Kerstin Eklund",
"01/300	Simon Sorensen",
"03/300	Kirstie Ibsen",
"06/300	Fabian Eklund",
"09/300	Halden Blomgren",
"10/300	Ruby Connolly",
"11/300	Colin Morris",
"12/300	Olson Solberg",
"13/300	Tobias Ibsen",
"17/300	Tamara Morris",
"21/300	Naoki Regan",
"22/300	Misaki Price",
"22/300	Hannah Jensen",
"23/300	David Holst",
"25/300	Helga Sorensen",
"27/300	Signe Solberg",
"03/301	Alice Morris",
"06/301	Berit Ibsen",
"08/301	Erik Eklund",
"10/301	Axel Sorensen",
"12/301	Ragnar Carlsen",
"13/301	Brenda Sorensen",
"14/301	Marie Eklund",
"18/301	Kaya Solberg",
"21/301	Matthias Solberg",
"21/301	Jana Bager",
"22/301	Vanessa Blomgren",
"23/301	Grace Murphy",
"25/301	Lukas Sorensen",
"26/301	Ebbe Jensen",
"26/301	Christian Eklund",
"27/301	Gunnar Jensen",
"01/302	Naoto Edwards",
"02/302	Sian Morris",
"03/302	Kirk Solberg",
"03/302	Tyr Solberg",
"04/302	Miho Collins",
"06/302	Nina Blomgren",
"15/302	Donar Blomgren",
"15/302	Gunnar Solberg",
"16/302	Leira Carlsen",
"17/302	Liam Lange",
"19/302	Elena Blomgren",
"21/302	Tyr Sorensen",
"22/302	Alexander Ibsen",
"22/302	Hannah McCarthy",
"25/302	Tamara Regan",
"26/302	Lucia Ibsen",
"28/302	Rina Price",
"01/303	Ryouta Edwards",
"05/303	Logan Edwards",
"08/303	Hallmar Solberg",
"08/303	Erik Blomgren",
"13/303	Sven Blomgren",
"15/303	Christian Sorensen",
"18/303	Sarah Solberg",
"21/303	Tyr Sorensen",
"22/303	Tate Yamada",
"22/303	Rina Price",
"23/303	Megan Sato",
"24/303	Dane Carlsen",
"03/304	Inge Sorensen",
"04/304	Henrik Solberg",
"08/304	Katie Carlsen",
"18/304	Lukas Jensen",
"20/304	Anamica Collins",
"22/304	Michael Blomgren",
"24/304	Agda Bager",
"25/304	Jamie Morris",
"27/304	Isabella Brown",
"28/304	Auna Morris",
"01/305	Pernille Eklund",
"01/305	Kaito Sato",
"05/305	Christopher Lenz",
"13/305	Sho Brown",
"14/305	Ella Solberg",
"20/305	Dahl Ibsen",
"03/306	Dean Price",
"11/306	Neena Morris",
"13/306	Emma McCarthy",
"13/306	Lilja Blomgren",
"20/306	Gala Solberg",
"21/306	Jonas Sorensen",
"23/306	Daichi Connolly",
"23/306	Anastasia Ibsen",
"26/306	Jessica Morris",
"28/306	Michelle Price",
"01/307	Tyr Solberg",
"04/307	Ashley Brown",
"10/307	Kirstie Blomgren",
"11/308	Conor McCarthy",
"16/308	Luke Connolly",
"19/308	Lutz Sauer",
"22/308	Maximilian Solberg",
"03/309	Ingrid Solberg",
"09/309	Sarah Solberg",
"11/309	Sakura Collins",
"11/309	Tobias Sorensen",
"14/309	Ian Sato",
"26/309	Tyra Sorensen",
"12/310	Pierrick Solberg",
"20/310	Tyra Solberg",
"08/311	William McCarthy",
"10/311	Kerstin Sorensen",
"15/311	Valdemar Sorensen",
"24/311	Ella Sorensen",
"28/311	Felix Thorn",
"28/311	Nanami Yamada"
)


Blonduos_sample_11=sample(Blonduos_birth_records, 11)
# manually checking how many of these people are alive, and if they are alive, if they consent
# to participate in the study.

# Hannah Jensen: alive and consents!
# Sakura Collins: alive but declined
# Sven Blomgren: deceased
# Elena Blomgren: alive and consented!
# Dean Price: ailve and consented.
# Ashley Brown, alive and consented
# Olson Solber: deceased
# Ian Sato: deceased
# Maximilian Solberg: alive but declined.
# Brenda Sorenson: alive and consented
# Emma McCarthy: deceased.

# obtained 5/11 participants. Need to re-sample 6 more people.
# removing the previous 11 values from the vector:

elements_to_remove=c("22/300	Hannah Jensen", "11/309	Sakura Collins", "13/303	Sven Blomgren",
  "19/302	Elena Blomgren", "03/306	Dean Price", "04/307	Ashley Brown", "12/300	Olson Solberg",
  "14/309	Ian Sato", "22/308	Maximilian Solberg", "13/301	Brenda Sorensen", 
  "13/306	Emma McCarthy")

Blonduos_birth_records <- Blonduos_birth_records[!(Blonduos_birth_records %in% elements_to_remove)]

Blonduos_sample_24=sample(Blonduos_birth_records, 24)
#print(Blonduos_sample_24)

# Gunnar Solberg: deceased
# Sian Morris: alive and consented (6/11)
# Jana Bager: consented (7/11)
# Agda Bager: deceased 
# Misaki Price: deceased
# Kaito Sato: deceased
# Pierrick Solberg: deceased
# Ella Solberg: declined consent
# Axel Sorensen: consented (8/11)
# Christian Sorensen: deceased
# Dane Carlsen: deceased
# Jonas Sorensen: consented (9/11)
# Christopher Lenz: deceased
# Leira Carlsen: deceased
# Matthias Solberg: deceased
# Tyr Solberg: declined consent
# Jessica Morris: deceased
# Lucia Ibsen: deceased
# Anastasia Ibsen: consented (10/11)
# Michelle Price: declined consent
# Jamie Morris: deceased
# Tate Yamada: deceased
# Megan Sato: deceased
# Ragnar Carlsen: consented. (11/11)

Blonduos_sample = c(
"22/300	Hannah Jensen",
"19/302	Elena Blomgren",
"03/306	Dean Price",
"04/307	Ashley Brown",
"13/301	Brenda Sorensen",
"02/302	Sian Morris",
"21/301	Jana Bager",
"10/301	Axel Sorensen",
"21/306	Jonas Sorensen",
"23/306	Anastasia Ibsen",
"12/301	Ragnar Carlsen"
)

Vardo_birth_records = c(
"02/300	Florian Lund",
"03/300	Sakura McCarthy",
"04/300	Ryan Murphy",
"04/300	Lisa Solberg",
"06/300	Haruka Watanabe",
"07/300	Haru Collins",
"08/300	Shiori Wilson",
"09/300	Justin Edwards",
"11/300	Emma Sorensen",
"11/300	Susannah Connolly",
"13/300	David Eklund",
"16/300	Siobhan Collins",
"16/300	Amy Wilson",
"19/300	Megan Yamada",
"19/300	Erla Larsen",
"19/300	Thurston Solberg",
"19/300	Astrid Carlsen",
"19/300	Christian Madsen",
"19/300	Mia Eklund",
"19/300	Arvid Eklund",
"20/300	Sophie Eklund",
"21/300	Henrik Sorensen",
"21/300	Dane Eklund",
"21/300	Kristina Lund",
"21/300	Lucia Solberg",
"22/300	Galen Bager",
"24/300	James Brown",
"24/300	Tyr Carlsen",
"24/300	Matthias Bager",
"25/300	Halle Sorensen",
"27/300	Jorn Pallesen",
"27/300	Hakan Sorensen",
"28/300	Gert Jensen",
"01/301	Erla Solberg",
"02/301	Sho Regan",
"03/301	Daniel Brown",
"07/301	Gerik Sorensen",
"09/301	Malena Carlsen",
"10/301	Vanessa Carlsen",
"10/301	Takumi Price",
"11/301	Daniel Blomgren",
"12/301	Tindra Solberg",
"13/301	Yorick Blomgren",
"13/301	Ragnar Carlsen",
"14/301	Kaeda Edwards",
"14/301	Mitchell Morris",
"16/301	Darren Wilson",
"16/301	Tatsuya Wilson",
"17/301	Kaya Thorn",
"18/301	Kenta Edwards",
"18/301	Harold Jensen",
"22/301	Emma Connolly",
"27/301	Hama Brown",
"27/301	Erling Carlsen",
"27/301	Sophia Carlsen",
"27/301	Amon Yamada",
"27/301	Joshua Yamada",
"01/302	Ingrid Sorensen",
"01/302	Tove Pallesen",
"02/302	Karen Madsen",
"02/302	Peter Hall",
"02/302	Florian Lund",
"02/302	Erling Solberg",
"02/302	Kristel Bergmann",
"03/302	Tyra Carlsen",
"03/302	Axel Sorensen",
"05/302	Shin Collins",
"05/302	Rin Kimura",
"06/302	Sigrid Blomgren",
"06/302	Gala Blomgren",
"10/302	Jasmin Solberg",
"11/302	Kristina Solberg",
"11/302	Ursula Solberg",
"13/302	Tove Carlsen",
"14/302	Simon Solberg",
"15/302	Katie Murphy",
"17/302	Gin Morris",
"18/302	Paul Blomgren",
"20/302	Alexis Dupont",
"22/302	Tomas Carlsen",
"23/302	Signe Carlsen",
"24/302	Liane Bauer",
"24/302	Marc Wagner",
"25/302	Gavin Connolly",
"01/303	Emma Carlsen",
"02/303	Ai Brown",
"04/303	Jarrod Hall",
"04/303	Grace Price",
"05/303	Grace Collins",
"05/303	Kirstie Sorensen",
"06/303	Inge Carlsen",
"07/303	Riko Jackson",
"07/303	Kirstie Jensen",
"09/303	Lucy Collins",
"13/303	Erin Kimura",
"13/303	Tobias Blomgren",
"14/303	Ella Madsen",
"14/303	David Olsen",
"18/303	Martina Lindner",
"21/303	Yorick Solberg",
"22/303	Sascha Guenther",
"23/303	Nils Eklund",
"23/303	Amy Collins",
"23/303	Taylor Collins",
"27/303	Sophia Blomgren",
"01/304	Christian Bager",
"03/304	Paige Wilson",
"04/304	Hunter Morris",
"07/304	Torvald Blomgren",
"07/304	Niamh Murphy",
"07/304	Nerina Yamada",
"07/304	Zoe Morris",
"07/304	Ralf Wenzel",
"10/304	Sonja Schulze",
"12/304	Katie Solberg",
"12/304	Ava Kimura",
"15/304	Dylan Collins",
"16/304	Kevin Brown",
"18/304	Sorena Eklund",
"22/304	Valdemar Erickson",
"24/304	Julian Eklund",
"24/304	Raphael Sorensen",
"27/304	Gemma Moore",
"28/304	Nana Jackson",
"01/305	Jacques Jacobsen",
"02/305	Tineka Thorn",
"04/305	Peter Wilson",
"05/305	Soeren Guenther",
"08/305	Daiki Kimura",
"11/305	Edgar Morris",
"13/305	Kayleigh Morris",
"15/305	Conor Connolly",
"17/305	Jarrod Summers",
"17/305	Ian Summers",
"21/305	Sten Sorensen",
"22/305	Per Peters",
"23/305	Brigit Clausen",
"01/306	Lars Carlsen",
"03/306	Jessica McCarthy",
"09/306	Vanessa Eklund",
"10/306	Sabrina Guenther",
"10/306	Ingrid Larsen",
"10/306	Philipp Mohr",
"13/306	Jonas Erickson",
"17/306	Delaney Kimura",
"04/307	Marcel Sorensen",
"08/307	Gunnar Eklund",
"22/307	Valerie Hardy",
"28/307	Daiki Edwards",
"28/307	Francois Page",
"05/308	Gabriele Schwarz",
"07/308	Liam Morris",
"14/308	Kevin Connolly",
"17/308	Gunnar Solberg",
"20/308	Kristel Sommer",
"21/308	Sian Wilson",
"25/308	Ruth Bauer",
"26/308	Macon Dupont",
"04/309	Helsa Lund",
"15/309	Daiki Wilson",
"15/309	Ryan Regan",
"22/309	Natalia Guenther",
"24/309	Bridey Kimura",
"27/309	Sten Solberg",
"10/310	Bernhard Guenther",
"13/310	Patrick Yamada",
"19/310	Rida Page",
"19/310	Regine Sommer",
"20/310	Yorick Sorensen",
"22/310	Mark Morris",
"22/310	Christopher Froehlich",
"25/310	Manan Mardia",
"01/311	Mitchell Regan",
"02/311	Klara Blomgren",
"03/311	Konstanze Busch",
"04/311	Ebbe Blomgren"
)

Vardo_sample_29=sample(Vardo_birth_records, 29)

# print(Vardo_sample_29)

# Sian Wilson: declined
# Christopher Froehlich: consented (1/11)
# Mana Mardia: consented (2/11)
# Harold Jensen: deceased
# Lucia Solberg: consented (3/11)
# Sophia Blomgren: consented (4/11)
# Martina Lindner: deceased
# Tove Pallesen: consented (5/11)
# Per Peters: consented (6/11)
# Lucy Collins: deceased
# Emma Connolly: consented (7/11)
# Tomas Carlsen: deceased
# Sascha Guenther: deceased
# Arvid Eklund: consented (8/11)
# Sten Solberg: deceased
# Karen Madsen: deceased
# Conor Connelly: consented (9/11)
# Raphael Sorensen: deceased
# Siobhan Collins: deceased
# Jessica McCarthy: deceased
# Grace Price: consented (10/11)
# Sophia Carlsen: deceased
# Sigrid Blomgren: deceased
# David Eklund: deceased
# Riko Jackson: deceased
# Ella Medsen: deceased
# James Brown: declined
# Natalia Guenther: deceased
# Vanessa Eklund: consented!

Vardo_sample <- c(
  "22/310\tChristopher Froehlich",
  "25/310\tMana Mardia",
  "21/300\tLucia Solberg",
  "27/303\tSophia Blomgren",
  "01/302\tTove Pallesen",
  "22/305\tPer Peters",
  "22/301\tEmma Connolly",
  "19/300\tArvid Eklund",
  "15/305\tConor Connelly",
  "04/303\tGrace Price",
  "09/306\tVanessa Eklund"
)
```

```{r}
set.seed(288)
Helvig_birth_records=c(
"01/300 Yorick Blomgren",
"02/300 Sakura Collins",
"05/300 Nico Jensen",
"06/300 Niamh Wilson",
"07/300 Elin Sorensen",
"08/300 Malena Sorensen",
"09/300 Ella Bager",
"10/300 Berit Carlsen",
"11/300 Lea Solberg",
"11/300 Sophie Blomgren",
"12/300 Brenda Solberg",
"15/300 Selina Sorensen",
"17/300 Nanami Collins",
"17/300 Olivia Sato",
"17/300 Ansel Page",
"18/300 Jessica Brown",
"18/300 Erika Olsen",
"20/300 Jorn Solberg",
"22/300 Brittany Suzuki",
"22/300 Malena Lund",
"23/300 Sinead Regan",
"24/300 Dahl Carlsen",
"25/300 Nanami Morris",
"25/300 Marie Blomgren",
"27/300 Tove Ibsen",
"28/300 Lars Blomgren",
"01/301 Olivia Watanabe",
"03/301 Sebastian Solberg",
"04/301 David Solberg",
"04/301 Chloe Wilson",
"05/301 Dean Edwards",
"05/301 Magdalena Carlsen",
"06/301 Gala Sorensen",
"08/301 Liam Watanabe",
"09/301 Kirk Solberg",
"09/301 Agda Solberg",
"12/301 Tindra Blomgren",
"12/301 Jack Wilson",
"13/301 Nathan Collins",
"14/301 Mike Collins",
"14/301 Laura Solberg",
"16/301 Lynnea Lund",
"17/301 Lynnea Ibsen",
"17/301 Olina Solberg",
"18/301 Kaya Lund",
"18/301 Olina Sorensen",
"19/301 Kirk Carlsen",
"22/301 Masa Sato",
"24/301 Thurston Lund",
"24/301 Sinead Moore",
"25/301 Colin Watanabe",
"26/301 Tyr Ibsen",
"27/301 Jamie Edwards",
"27/301 Asuka Brown",
"27/301 Helsa Solberg",
"28/301 Minh Regan",
"28/301 Emily Regan",
"28/301 Julia Lund",
"04/302 Maya Wilson",
"05/302 Olson Jensen",
"07/302 Jeneve Carlsen",
"09/302 Emma Blomgren",
"10/302 Britt Holst",
"11/302 Ebbe Carlsen",
"13/302 Megane Dupont",
"15/302 Tobias Lund",
"15/302 Kari Bager",
"21/302 Tyra Sorensen",
"21/302 Tyra Blomgren",
"23/302 Ashley Murphy",
"23/302 Rin Morris",
"23/302 Ronan Hall",
"23/302 Henning Neumann",
"23/302 Nikola Langer",
"25/302 Brigit Solberg",
"25/302 Krista Scholz",
"27/302 Grace Wilson",
"28/302 Naoki Edwards",
"28/302 Donar Solberg",
"01/303 Florian Solberg",
"03/303 Edgar Edwards",
"03/303 Kerstin Sorensen",
"04/303 Hannah Collins",
"06/303 Allana Wilson",
"07/303 Emily Regan",
"08/303 Gin McCarthy",
"10/303 Jakob Blomgren",
"10/303 Karin Richter",
"11/303 Miki Moore",
"12/303 Monika Hahn",
"13/303 Inge Sorensen",
"13/303 Akane Brown",
"14/303 Nikolaus Gruber",
"15/303 Nils Carlsen",
"17/303 Ren Edwards",
"20/303 Daniel Solberg",
"21/303 Ole Sorensen",
"25/303 Neena Kimura",
"25/303 Cariel Solberg",
"02/304 Michelle Wilson",
"04/304 Arvid Solberg",
"07/304 Liam Collins",
"08/304 Camille Delacroix",
"08/304 Tobias Blomgren",
"09/304 Illona Blomgren",
"13/304 Gerald Reinhardt",
"15/304 Pernille Carlsen",
"15/304 Anika Solberg",
"16/304 Robert Maier",
"19/304 Bert Meyer",
"19/304 Karsten Hartmann",
"20/304 Karena Lund",
"24/304 Christian Lund",
"24/304 Lawrence Hall",
"24/304 Birte Hahn",
"27/304 Anthony Collins",
"01/305 Jordan Brown",
"03/305 Jolanta Richter",
"04/305 Lars Solberg",
"06/305 Raum Blomgren",
"09/305 Florian Blomgren",
"09/305 Maike Neumann",
"12/305 Lars Sorensen",
"12/305 Sean Morris",
"13/305 Signe Sorensen",
"16/305 Raum Solberg",
"16/305 Shiori Wilson",
"17/305 Maya Wilson",
"26/305 Florian Carlsen",
"04/306 Emma Thorn",
"05/306 Sven Carlsen",
"09/306 Auna Hall",
"09/306 Nathan Hall",
"12/306 Britt Blomgren",
"19/306 Erik Beyer",
"21/306 Lucy McCarthy",
"26/306 Lucia Sorensen",
"28/306 Felix Sorensen",
"28/306 Monika Schumann",
"22/307 Emily Kimura",
"15/308 Corinna Hoffmann",
"17/308 Kirstie Larsen",
"19/308 Reinhardt Voigt",
"22/308 Elin Blomgren",
"04/309 Ryan Kimura",
"08/309 Aimon Hardy",
"09/309 Adam Stein",
"10/309 Leanne Davidson",
"17/309 Kevin Edwards",
"23/309 Anund Olsen",
"24/309 Katarina Lenz",
"24/309 Petra Wagner",
"25/309 Tatjana Gruber",
"01/310 Marcel Solberg",
"01/310 Valentina Langer",
"01/310 Josh Kimura",
"04/310 Ulrich Bergmann",
"05/310 Jake Murphy",
"08/310 Henri Langer",
"14/310 Raum Carlsen",
"14/310 Kosaku Yamasaki",
"28/310 Rita Voigt",
"02/311 Malena Blomgren",
"03/311 Astrid Richter")

Helvig_sample_11=sample(Helvig_birth_records, 11)
print(Helvig_sample_11)
#"17/300 Nanami Collins" Declined   
#"27/301 Asuka Brown"      
#"19/304 Karsten Hartmann"
#"16/305 Shiori Wilson"    
#"17/301 Lynnea Ibsen" Consented    
#"28/302 Naoki Edwards"  
#"11/303 Miki Moore"       
#"21/306 Lucy McCarthy"    
#"25/303 Cariel Solberg" Consented  
#"15/303 Nils Carlsen"     
#"23/309 Anund Olsen"

#2/11

elements_to_remove=c("17/300 Nanami Collins", "27/301 Asuka Brown", "19/304 Karsten Hartmann", "16/305 Shiori Wilson", "17/301 Lynnea Ibsen", "28/302 Naoki Edwards", "11/303 Miki Moore", "21/306 Lucy McCarthy", "25/303 Cariel Solberg", "15/303 Nils Carlsen", "23/309 Anund Olsen")

Helvig_birth_records <- Helvig_birth_records[!(Helvig_birth_records %in% elements_to_remove)]

Helvig_sample_24=sample(Helvig_birth_records, 31)
print(Helvig_sample_24)
#"28/310 Rita Voigt" Consented
# Arvid Solberg Consented
# Kevin Edwards Consented
# Raum Carlsen Consented
# Olina Sorensen Consented
# Pernille Carlsen consented
# Gerald Reinhardt Consented
# Katarina Lenz Consented
# Signe Sorensen Consented
#11/11

#Final Helvig Sample
#"17/301 Lynnea Ibsen"
#"25/303 Cariel Solberg"
#"28/310 Rita Voigt" Consented
# 04/304 Arvid Solberg Consented
# 17/309 Kevin Edwards Consented
# 14/310 Raum Carlsen Consented
# 18/301 Olina Sorensen Consented
# 15/304 Pernille Carlsen consented
# 13/304 Gerald Reinhardt Consented
# 24/309 Katarina Lenz Consented
# 13/305 Signe Sorensen consented.
```

```{r}
set.seed(288)
Biruwa_birth_records=c(
"01/300 Nana Morris",
"02/300 Takuya Sato",
"05/300 Ursula Eklund",
"09/300 Jessica Moore",
"10/300 Tyr Lund",
"10/300 Mizuki Collins",
"14/300 Katie Jackson",
"16/300 Ryan Kimura",
"19/300 Yorick Lund",
"19/300 Hama Connolly",
"20/300 Mary Edwards",
"21/300 Sarah Bager",
"22/300 Gunnar Sorensen",
"23/300 Kayleigh Kimura",
"23/300 Elias Larsen",
"24/300 Julian Carlsen",
"24/300 Justin Price",
"26/300 Kerstin Ibsen",
"26/300 Leah Davies",
"27/300 Nicholas Collins",
"28/300 Tyr Sorensen",
"28/300 Jackson Wilson",
"02/301 Ruby Kimura",
"02/301 Nanami Morris",
"04/301 Leif Blomgren",
"05/301 Megan Watanabe",
"08/301 Cameron McCarthy",
"13/301 Colin Collins",
"13/301 Ren Brown",
"19/301 Gunnar Thorn",
"19/301 Rosalind Lund",
"24/301 Samantha Connolly",
"24/301 Zoe Sato",
"02/302 Gavin Morris",
"06/302 Sten Ibsen",
"06/302 Pantea Sorensen",
"06/302 Lars Blomgren",
"11/302 Fabian Sorensen",
"13/302 Yuka Watanabe",
"19/302 Daichi Morris",
"21/302 Josh Collins",
"22/302 Akira Sato",
"23/302 Ole Bager",
"24/302 Ole Jensen",
"24/302 Harold Jensen",
"25/302 Hannah McCarthy",
"01/303 Anastasia Blomgren",
"04/303 Gavin Connolly",
"10/303 Mark Wilson",
"11/303 Daiki Brown",
"17/303 Scott McCarthy",
"18/303 Aya Connolly",
"19/303 Olina Carlsen",
"23/303 Chloe Collins",
"23/303 Haruka Collins",
"24/303 Matthias Carlsen",
"25/303 Taylor Morris",
"26/303 Daichi Wilson",
"28/303 Yuta Morris",
"07/304 Mia Jensen",
"13/304 Tate Moore",
"13/304 Logan Edwards",
"14/304 Jacob Connolly",
"24/304 Sarah Solberg",
"28/304 Riley Wilson",
"12/305 Arvid Jensen",
"16/305 Britt Eklund",
"17/305 Harry McCarthy",
"18/305 Cariel Blomgren",
"20/305 Marcus Yamada",
"27/305 Arvid Jensen",
"28/305 Adam Wilson",
"01/306 Gemma Morris",
"04/306 Remy Connolly",
"08/306 Sylvain Vasseur",
"11/306 Nanami Kimura",
"27/306 Maximilian Jensen",
"01/307 Mayu Morris",
"11/307 Neil McKay",
"14/307 Berangere Pons",
"14/307 Taylor Moore",
"18/307 Tobias Eklund",
"23/307 Lucas Yamada",
"25/307 Nanami Jones",
"26/307 Sophia Ibsen",
"09/308 Nanami Morris",
"09/308 Natascha Girard",
"15/308 Daniel Kimura",
"24/308 Liliane Gautier",
"24/308 Chanda Babu",
"01/309 Erin Collins",
"11/309 Hans Blomgren",
"13/309 Cyril Pelletier",
"18/309 Max Leger",
"21/309 Keerthana Chunduri",
"23/309 Cameron Morris",
"24/309 Torvald Carlsen",
"07/310 Nirvan Dhar",
"13/310 Rin Connolly",
"15/310 Claudie Leger",
"15/310 Tomas Bager",
"19/310 Yanick Gautier",
"20/310 Esha Mehta",
"23/310 Killian McCarthy",
"26/310 Eliane Besson",
"27/310 Paresh Datta",
"03/311 Gayan Babu",
"04/311 Layak Mardia",
"10/311 Lee Moore",
"12/311 Aadesh Bhatt",
"14/311 Tyra Blomgren",
"14/311 Tindra Eklund",
"14/311 Emaan Kulkarni",
"16/311 Daniel Ibsen",
"20/311 Patricia Price",
"20/311 Suvarna Ganaka",
"22/311 Ryouta McCarthy",
"24/311 Akane Connolly")

Biruwa_sample_11=sample(Biruwa_birth_records, 11)
print(Biruwa_sample_11)

# Liliane Gautier
# Torvald Carlsen
# Ryan Kimura

#3/11

elements_to_remove=c("22/300 Gunnar Sorensen", "14/311 Tyra Blomgren", "24/308 Liliane Gautier",
  "18/309 Max Leger", "24/309 Torvald Carlsen", "23/302 Ole Bager", "16/300 Ryan Kimura",
  "28/300 Jackson Wilson", "23/303 Chloe Collins", "01/307 Mayu Morris", 
  "13/310 Rin Connolly")

Biruwa_birth_records <- Biruwa_birth_records[!(Biruwa_birth_records %in% elements_to_remove)]

Biruwa_sample_24=sample(Biruwa_birth_records, 35)
print(Biruwa_sample_24)

# Sarah Bager
# Killian McCarthy
# Nanami Kimura
# Tobias Eklund
# Remy Connolly
# Cariel Blomgren
# Chanda Babu
# Sarah Solberg
#11/11

#Final Biruwa sample:
# 24/308 Liliane Gautier
# 24/309 Torvald Carlsen
# 16/300 Ryan Kimura
# 21/300 Sarah Bager
# 23/310 Killian McCarthy
# 11/306 Nanami Kimura
# 18/307 Tobias Eklund
# 04/306 Remy Connolly
# 18/305 Cariel Blomgren
# 24/308 Chanda Babu
# 24/304 Sarah Solberg

Shinobi_sample <- sample(Shinobi_birth_records, 30)
print(Shinobi_sample)

# 05/312 Juhani Ibsen 
# 20/315 Matthew Brown DECEASED 
# 09/306 Lena Olsen 
# 19/319 Mia Yamada
# 06/300 Elsa Thorn DECEASED
# 22/318 Ophelia Eklund DECEASED 
# 08/318 Kashvi Kumar 
# 07/301 Viggo Sorensen
# 26/300 Ava Collins 
# 14/305 Simon (Marshall) Sorensen
# 24/314 Taylor Morris DECEASED
# 06/308 Zachary Kimura DECEASED 
# 02/312 Michelle Moore DECLINED
# 01/303 Akane Watanabe
# 23/316 Shane Sato 
# 13/311 Kerstin Thorn 
# 09/319 Amy Brown DECLINED 
# 16/303 Desmond Connolly DECEASED 
# 22/318 Ophelia Eklund DECEASED 
# 11/318 Hiro Kimura DECLINED 
# 27/318 Benjamin Wilson



Reading_birth_records <- c(
"21/300 Mia Regan",
"21/300 Alexander Watanabe",
"21/300 Sophia Connolly",
"21/300 Riku Price",
"21/300 Ryan Jackson",
"22/300 Sven Solberg",
"25/300 Mike McCarthy",
"25/300 Michaela Sato",
"25/300 Hans Carlsen",
"25/300 Lucia Solberg",
"27/300 Raphael Solberg",
"27/300 Ryouta Connolly",
"02/301 Samuel Eklund",
"03/301 Takumi Roberts",
"04/301 Viggo Blomgren",
"04/301 Karena Jensen",
"06/301 Brittany McCarthy",
"07/301 Bronwyn Wilson",
"08/301 Anais Wilson",
"09/301 Sanna Sorensen",
"09/301 Gretel Solberg",
"10/301 Takahiro McCarthy",
"11/301 Noah Morris",
"11/301 Bernard Dupont",
"13/301 Felix Olsen",
"15/301 Galen Lund",
"15/301 Anamica Morris",
"15/301 Brigit Jensen",
"17/301 Ruby McCarthy",
"17/301 Akane Collins",
"17/301 Liliane Dupuy",
"19/301 Manami Moore",
"19/301 Tomas Larsen",
"19/301 Monica Crawford",
"21/301 Lucy Sato",
"21/301 Mika Fukuda",
"22/301 Saika Connolly",
"22/301 Akari Nakano",
"23/301 Kelvin Hill",
"24/301 Olson Pallesen",
"24/301 Yui Moore",
"25/301 Katie Sato",
"25/301 Liam Morris",
"25/301 Ava Wilson",
"26/301 Kazuya Suzuki",
"26/301 Niall Black",
"27/301 Tate Kimura",
"27/301 Taichi Hara",
"28/301 Shiori Regan",
"01/302 Emma Kimura",
"01/302 Kirstie Solberg",
"02/302 Rumi Matsui",
"03/302 Karina Blomgren",
"03/302 Sarah Regan",
"03/302 Rosalind Crawford",
"04/302 Michael Jensen",
"04/302 Kerr Findlay",
"04/302 Magalie Besson",
"05/302 Rina Morris",
"05/302 Albert Lenz",
"05/302 Derick Hughes",
"05/302 Max Hernandez",
"06/302 Raphael Sorensen",
"07/302 Sarah Jackson",
"08/302 Marcel Ibsen",
"08/302 Jagan Srinivasan",
"09/302 David Sorensen",
"09/302 Jocelyne Lacroix",
"11/302 Daniel Sato",
"11/302 Matthew Sato",
"11/302 Kisho Murakami",
"12/302 Mathew Fraser",
"12/302 Shuta Koyama",
"12/302 Musashi Takeuchi",
"13/302 Nicole Jones",
"13/302 Takero Hashimoto",
"14/302 Ian Wilson",
"14/302 Jeneve Solberg",
"14/302 Ella Solberg",
"14/302 Josh Davies",
"14/302 Christian McIntyre",
"14/302 Yasuji Wada",
"14/302 Akeno Taketa",
"14/302 Takehiro Fujii",
"15/302 Lahar Gadhavi",
"16/302 Benjamin Brown",
"16/302 Louisa Scott",
"17/302 Raphael Eklund",
"17/302 Sara Muir",
"17/302 Wayne Williamson",
"17/302 Daryl Johnston",
"17/302 Andre Lefevre",
"18/302 Shelley Fraser",
"19/302 Theresa Bager",
"19/302 Leona Duncan",
"19/302 Auna Morris",
"19/302 Toshiya Miyasaki",
"19/302 Fabienne Fournier",
"20/302 Mia Solberg",
"20/302 Sarah Bager",
"20/302 Lars Solberg",
"20/302 Eva Connolly",
"20/302 Tove Solberg",
"20/302 Maja Mueller",
"20/302 Philippe Benoit",
"20/302 Regis Prevost",
"21/302 Josh Kimura",
"21/302 Jasmin Solberg",
"22/302 Aaron Wilson",
"22/302 Ross Brown",
"22/302 Adrienne Hughes",
"24/302 Conor Wilson",
"24/302 Lucien Dupont",
"24/302 Lyn Bell",
"24/302 Ann Johnstone",
"24/302 Gregg Hill",
"25/302 Rinsho Iwasaki",
"26/302 Sarah Erickson",
"26/302 Kimi Miura",
"26/302 Emaan Mishra",
"27/302 Lynnea Bager",
"27/302 Kimiko Takagi",
"27/302 Lionel Bourgeois",
"28/302 Emma Bager",
"28/302 Raphael Thorn",
"28/302 Linzi Robertson",
"28/302 Victor Black", 
"28/307 Luis Bonnet",
"01/308 Renaud Mallet",
"02/308 Mariko Endo",
"03/308 Elena Carlsen",
"04/308 Jack Price",
"04/308 Geraldine Alexander",
"05/308 Paige Jones",
"05/308 Geraldine Kerr",
"06/308 Sylvia Ritchie",
"06/308 Kaori Yamasaki",
"09/308 Herbert Huber",
"10/308 Melissa Connolly",
"10/308 Ayami Miyasaki",
"10/308 Akiyo Ichikawa",
"11/308 Vincent Lund",
"12/308 Belle Regan",
"13/308 Adam Morris",
"14/308 Ella Bager",
"14/308 Ragnar Olsen",
"16/308 Kamal Mishra",
"18/308 Maximilian Blomgren",
"18/308 Paige McCarthy",
"18/308 Barbara Meier",
"19/308 Connor Watanabe",
"19/308 Arthur Morris",
"19/308 Soji Fujihara",
"19/308 Kanehiro Okada",
"19/308 Cheryl Boyle",
"22/308 Armand Dupont",
"22/308 Kanehiro Yokoyama",
"23/308 Joel Masson",
"24/308 Anand Mehta",
"24/308 Risa Nakajima",
"25/308 Gunter Pfeiffer",
"27/308 Henrik Thorn",
"28/308 Takaji Ando",
"28/308 Ananya Gadhavi",
"01/309 Olson Ibsen",
"01/309 Kento Kaneko",
"04/309 Nayan Kaur",
"04/309 Lomash Kaur",
"05/309 Anthea Scott",
"05/309 Hiyori Fukuda",
"06/309 Ryotaro Miyamoto",
"07/309 Siobhan Hall",
"07/309 Aude Garnier" 
) 

Reading_sample <- sample(Reading_birth_records, 50)
print(Reading_sample)

# 20/302 Lars Solberg
# 05/302 Derick Hughes
# 07/301 Bronwyn Wilson DECEASED 
# 19/302 Fabienne Fournier DECEASED 
# 02/301 Samuel Eklund DECLINED 
# 22/302 Adrienne Hughes DECEASED 
# 17/302 Sara Muir DECEASED 
# 19/302 Theresa Bager
# 22/301 Saika Connolly DECEASED 
# 06/302 Raphael Sorensen DECEASED 
# 09/302 Jocelyne Lacroix DECEASED 
# 11/301 Noah Morris
# 14/302 Josh Davies
# 20/302 Mia Solberg DECEASED 
# 14/302 Jeneve Solberg
# 03/302 Sarah Regan DECEASED 
# 09/301 Gretel Solberg
# 28/302 Emma Bager DECEASED 
# 01/302 Kirstie Solberg DECLINED 
# 10/301 Takahiro McCarthy DECEASED 
# 17/301 Liliane Dupuy DECEASED 
# 27/300 Raphael Solberg DECEASED 
# 24/302 Lyn Bell DECEASED 
# 24/308 Risa Nakajima DECEASED 
# 04/309 Lomash Kaur
# 18/308 Maximilian Blomgren DECLINED 
# 22/302 Adrienne Hughes DECEASED 
# 14/308 Ragnar Olsen
# 18/308 Barbara Meier DECEASED 
# 23/308 Joel Masson 
# 06/308 Sylvia Ritchie
```

```{r}
set.seed(288)
#Bonne Sante Cities - Talu, Eden, Valais
Talu_birth_records = c("01/300	Tyra Carlsen",
"02/300	Allana Sato",
"04/300	Gala Eklund",
"04/300	Nina Ibsen",
"05/300	Anthony Watanabe",
"05/300	Emma Carlsen",
"08/300	Sakura Yamada",
"09/300	Celine Page",
"10/300	Florian Jensen",
"11/300	Galen Ibsen",
"17/300	Dane Sorensen",
"18/300	Ansel Sorensen",
"18/300	Hailey Edwards",
"19/300	Gaston Svendsen",
"21/300	Juhani Bager",
"21/300	Brenda Blomgren",
"22/300	Emma Jensen",
"24/300	Marshall Thorn",
"25/300	Natalie Pallesen",
"27/300	Marshall Lund",
"27/300	Auguste Lund",
"01/301	Minh Sato",
"01/301	Jarrod Wilson",
"01/301	Elise Suzuki",
"02/301	Brielle Jensen",
"04/301	Brigit Jensen",
"06/301	Eleanor Carlsen",
"06/301	Kaeda Watanabe",
"06/301	Rupert Solberg",
"06/301	Alexander Solberg",
"07/301	Hama Kimura",
"09/301	Samuel Dupont",
"10/301	Beau Connolly",
"11/301	Ingrid Svendsen",
"13/301	Ole Blomgren",
"13/301	Chloe Sato",
"13/301	Magritte Morris",
"14/301	Kate Hall",
"15/301	Nina Carlsen",
"17/301	Rachida Carre",
"18/301	Simon Faure",
"20/301	Magnar Carlsen",
"27/301	Megane Sato",
"27/301	Chryselle Sato",
"28/301	Rene Thorn",
"03/302	Rose Sato",
"04/302	Megane Swift",
"05/302	Ariane Suzuki",
"07/302	Rachelle Bager",
"08/302	Tove Jensen",
"10/302	Anamica Jones",
"10/302	Florent Reynaud",
"12/302	Bronwyn Watanabe",
"12/302	Sophia Watanabe",
"13/302	Tahlia Jensen",
"13/302	Jordan Wilson",
"14/302	Laurie Simon",
"15/302	Simon Eklund",
"16/302	Alexandre Blomgren",
"17/302	Orla Morris",
"19/302	Rupert Wilson",
"19/302	Celine Connolly",
"20/302	Alexander Wilson",
"24/302	Kristjana Sorensen",
"24/302	Rachelle Jensen",
"24/302	Kristina Faure",
"26/302	Harold Eklund",
"26/302	Manuel Levy",
"27/302	Shin Hall",
"27/302	Axel Blomgren",
"27/302	Corina Sato",
"28/302	Sylvaine Lecomte",
"02/303	Naoki Edwards",
"03/303	Kaeda Sato",
"04/303	Rene Connolly",
"06/303	Marcel Eklund",
"09/303	Audrey Svendsen",
"09/303	Samuel Suzuki",
"13/303	Charles Jensen",
"14/303	Micheline Carre",
"15/303	Mason Sato",
"17/303	Juhani Jensen",
"19/303	Nanami Jones",
"21/303	Gemma Wilson",
"23/303	Rosalind Jensen",
"23/303	Ai Kimura",
"27/303	Noelle Germain",
"28/303	Helene Wilson",
"28/303	Erika Eklund",
"03/304	Leon Sorensen",
"04/304	Astrid Eklund",
"06/304	Rosalie Abel",
"07/304	Olivier Simon",
"10/304	Frederique Jensen",
"12/304	Holly Sato",
"12/304	Louisa Jensen",
"12/304	Jermaine Hall",
"13/304	Mizuki Brown",
"16/304	Magritte Herbert",
"16/304	Jeremy Carlsen",
"16/304	Chantel Lund",
"19/304	Sarah Suzuki",
"27/304	Theresa Blomgren",
"01/305	Erling Bager",
"03/305	Beau Bager",
"05/305	Torsten Carlsen",
"08/305	Kana Price",
"08/305	Louisa Blomgren",
"09/305	Josette Morris",
"09/305	Blade Edwards",
"13/305	Rachelle Carlsen",
"17/305	Yorick Jensen",
"18/305	Pierrick Jensen",
"20/305	Lena Eklund",
"20/305	Hallmar Solberg",
"21/305	Rosalie Blomgren",
"21/305	Jules Suzuki",
"25/305	Anna Sorensen",
"03/306	Alexis Wilson",
"03/306	Holly Suzuki",
"05/306	Saeed Laha",
"08/306	Annabelle Abel",
"14/306	Fay Jensen",
"16/306	Jeremy Sato",
"17/306	Danielle Guillot",
"18/306	Jade Gagnon",
"18/306	Sebastian Svendsen",
"20/306	Vilina Gadhavi",
"21/306	Emy Jensen",
"21/306	Ragnar Bager",
"22/306	Mia Watanabe",
"24/306	Alicia Bager",
"24/306	Mai Edwards",
"24/306	Claire Carlsen",
"25/306	Nicolas Wilson",
"26/306	Grace Brown",
"01/307	Gabrielle Sorensen",
"09/307	Philipp Sorensen",
"14/307	Amon Suzuki",
"14/307	Pranay Tiwari",
"18/307	Damini Gadhavi",
"21/307	Jack Watanabe",
"27/307	Jake Summers",
"28/307	Killian Sato",
"03/308	Taylor Wilson",
"03/308	Gildas Gaillard",
"03/308	Pantea Sorensen",
"04/308	Marilyn Leger",
"06/308	Percival Carlsen",
"06/308	Felix Blomgren",
"06/308	Harvey Dupont",
"07/308	Gaetan Jensen",
"07/308	Laurie Morris",
"09/308	Corine Germain",
"10/308	Aurore Aubert",
"13/308	Gavin Wilson",
"17/308	Daiki Yamada",
"19/308	Brenda Erickson",
"20/308	King Suzuki",
"23/308	Liliane Dupuy",
"01/309	Pierre Swift",
"01/309	Pahal Ahmad",
"02/309	Justin Connolly",
"02/309	Patrick Moore",
"02/309	Kevin Moore",
"02/309	Manuella Dupuis",
"04/309	Oviyan Gadhavi",
"05/309	Claire Sato",
"08/309	Jeannine Marques",
"09/309	Jacques Simon",
"09/309	Oviyan Basu",
"10/309	Inge Jensen",
"11/309	Michaela Kimura",
"12/309	Emma Blomgren",
"14/309	Chloe McCarthy",
"15/309	Julia Solberg",
"18/309	Ramya Sharma",
"19/309	Prasad Babu",
"20/309	Chahel Lingutla",
"21/309	Anushka Ghosh",
"26/309	Jacob Morris",
"27/309	Delaney Jones",
"27/309	Rachida Dupuy",
"27/309	Suhanisa Ramanan",
"02/310	Anund Ibsen",
"02/310	Julia Suzuki",
"04/310	Hunter Kimura",
"07/310	Sylvie Marques",
"08/310	Charles Jensen",
"10/310	Rina Varadkar",
"14/310	Danielle Morel",
"14/310	Rahas Babu",
"16/310	Nanako Watanabe",
"16/310	Joaquim Duval",
"17/310	Axel Larsen",
"17/310	Gildas Dupuis",
"18/310	Takuya Moore",
"22/310	Arya Ahmad",
"22/310	Fatima Legros",
"23/310	Rosalie Sorensen",
"23/310	Regis Lemoine",
"23/310	Antonio Maury",
"27/310	Paresh Lingutla",
"27/310	Naina Chatterjee",
"07/311	Anushka Bose",
"09/311	Sarah Basu",
"09/311	Kaia Gadhavi",
"12/311	Madeleine Gillet",
"12/311	Ketan Ramanan",
"13/311	Philippe Marques",
"17/311	Gaston Morris",
"17/311	France Bouchet",
"18/311	Shannon Watanabe",
"20/311	Hakan Larsen",
"21/311	Pascal Duval",
"23/311	Zaina Bahadur",
"23/311	Justin Abbasi",
"26/311	Louisa Connolly",
"27/311	Daiki Sato",
"28/311	Davignon Ibsen")
Talu_sample <- sample(Talu_birth_records, 31) #Increased in a stepwise fashion until the correct amount is obtained
print(Talu_sample)
# 16/304 Chantel Lund: DEAD
# 05/306 Saeed Laha: DEAD
# 20/309 Chahel Lingutla: DECLINED
# 19/302 Rupert Wilson: DECLINED
# 19/308 Brenda Erickson: CONSENTED (1/11)
# 04/300 Gala Eklund: DEAD
# 03/308 Gildas Gaillard: CONSENTED (2/11)
# 25/306 Nicolas Wilson: CONSENTED (3/11)
# 03/308 Charles Jensen: DEAD
# 27/300 Auguste Lund: DEAD 
# 18/300 Hailey Edwards: DECLINED
# 12/302 Sophia Watanabe: DEAD
# 13/305 Rachelle Carlsen: DEAD 
# 18/306 Sebastian Svendsen: DEAD
# 27/301 Megane Sato: CONSENTED (4/11)
# 09/303 Samuel Suzuki: DEAD
# 28/303 Erika Eklund: CONSENTED (5/11)
# 26/306 Grace Brown: DEAD
# 16/304 Magritte Herbert: CONSENTED (6/11)
# 10/304 Frederique Jensen: DEAD
# 06/308 Felix Blomgren: DEAD
# 13/301 Magritte Morris: CONSENTED (7/11)
# 20/308 King Suzuki: DEAD
# 06/308 Harvey Dupont: DEAD
# 14/310 Danielle Morel: DEAD
# 14/307 Amon Suzuki: CONSENTED (8/11)
# 26/302 Manuel Levy: DECLINED
# 23/310 Regis Lemoine: DECLINED
# 03/304 Leon Sorensen: CONSENTED (9/11)
# 20/311 Hakan Larsen: CONSENTED (10/11)
# 14/310 Rahas Babu: CONSENTED (11/11)
```

```{r}
set.seed(288)
#Bonne Sante Cities - Talu, Eden, Valais
Eden_birth_records <- c("01/300 Sanna Carlsen",
"03/300 Dionne Hall",
"04/300 Lamont Page",
"07/300 Elie McCarthy",
"13/300 Rida Lund",
"14/300 Henri Petit",
"18/300 Claire Watanabe",
"20/300 Marshall Edwards",
"20/300 Alicia Dupont",
"22/300 Nanami McCarthy",
"22/300 Antoine Connolly",
"22/300 Gaston Connolly",
"23/300 Beatrice Solberg",
"24/300 Zoe Sato",
"26/300 Asuka Kimura",
"28/300 Kayleigh Edwards",
"03/301 Sophia Wilson",
"03/301 Alexia Blomgren",
"04/301 Mizuki Edwards",
"05/301 Erika Sorensen",
"05/301 Nico Lund",
"06/301 Jack Kimura",
"07/301 Nicolas Connolly",
"07/301 Phoebe Edwards",
"08/301 Gustave Solberg",
"10/301 Etienne Lund",
"12/301 Nico Solberg",
"17/301 Louisa Dupont",
"21/301 King Connolly",
"23/301 Hiro Sato",
"24/301 Rene Morris",
"27/301 Philipp Larsen",
"01/302 Mathis Dupont",
"02/302 Daiki Summers",
"03/302 Alice White",
"04/302 Charles Herbert",
"07/302 Laasya Srinivasan",
"09/302 Elie Murphy",
"10/302 Melissa McCarthy",
"10/302 Teala Eklund",
"10/302 Liam Morris",
"10/302 Aadesh Singh",
"11/302 Yvonne Petit",
"12/302 Beau Solberg",
"13/302 Alexia Thorn",
"14/302 Marcus Burke",
"17/302 Aimee Abel",
"18/302 Zachary Simon",
"21/302 Claudette Simon",
"22/302 Neena Sato",
"23/302 Patrick Wilson",
"24/302 Hama Edwards",
"27/302 Hina Swift",
"27/302 Rin Connolly",
"28/302 Orla Edwards",
"28/302 Thevan Kumar",
"01/303 Gabriel Connolly",
"03/303 Seymour Yamada",
"04/303 Conor Wilson",
"07/303 Gabriel Dupont",
"07/303 Fabrice Dupont",
"09/303 Gert Larsen",
"09/303 Nils Larsen",
"09/303 Joshua Morris",
"09/303 Johanna Solberg",
"15/303 Paavan Basu",
"16/303 Armand Petit",
"18/303 Anamica Connolly",
"19/303 Hallmar Pallesen",
"19/303 Jorn Solberg",
"20/303 Mason Thorn",
"21/303 King Brown",
"22/303 Takuya Kimura",
"22/303 Akane Hall",
"22/303 Dheer Basu",
"24/303 Ole Solberg",
"27/303 Ayano Sato",
"27/303 Justin Herbert",
"27/303 Momoko Edwards",
"27/303 Rachelle Hall",
"01/304 Georgina Suzuki",
"02/304 Yvonne Perrot",
"02/304 Abbey Price",
"03/304 Gyan Varma",
"06/304 Thurston Carlsen",
"06/304 Naoto Summers",
"07/304 Neena Sato",
"09/304 Sahana Ramanan",
"09/304 Nirvan Kulkarni",
"09/304 Yuval Kulkarni",
"10/304 Sage Yamada",
"12/304 Harry Wilson",
"12/304 Rushil Devar",
"14/304 Keerthana Shah",
"15/304 Maxine Bager",
"16/304 Ethan Swift",
"16/304 Fay Pallesen",
"18/304 Jacques Wilson",
"18/304 Kaia Ramanujan",
"19/304 Tomas Solberg",
"23/304 Chahna Ramanan",
"25/304 Macon Sato",
"25/304 Jasmin Solberg",
"26/304 Magritte Pallesen",
"03/305 Amber Suzuki",
"03/305 Haru Sato",
"04/305 Delaney Edwards",
"06/305 Kamala Patel",
"08/305 Claire Simon",
"10/305 Sorena Blomgren",
"10/305 Avril Carlsen",
"10/305 Inesh Ramanan",
"12/305 Blaise McCarthy",
"12/305 Rose Yamada",
"12/305 Dheer Bhatt",
"15/305 Pierre Bager",
"15/305 Miki Watanabe",
"19/305 Marcus Wilson",
"19/305 Harvey Thorn",
"21/305 Mana Shah",
"22/305 Denis Wilson",
"23/305 Chaman Kaur",
"25/305 Belle Abel",
"26/305 Pavak Basu",
"28/305 Davignon Perrot",
"28/305 Ajay Pillai",
"01/306 Henrik Allard",
"01/306 Tomas Allard",
"02/306 Shota Jones",
"03/306 William Edwards",
"03/306 Akira McCarthy",
"03/306 Taahira Ramanujan",
"04/306 Eva Brown",
"04/306 Pia Ganaka",
"04/306 Yuval Devar",
"05/306 Elle Dupont",
"05/306 Mangala Dayal",
"06/306 Thibaud Brun",
"07/306 Kaia Chatterjee",
"07/306 Rushil Dhar",
"09/306 Arnaud Monnier",
"13/306 Ansel Herbert",
"14/306 Nayan Agarwal",
"15/306 Benjamin Connolly",
"15/306 Bindi Tamboli",
"16/306 Maalai Mardia",
"18/306 Nicolas Pallesen",
"19/306 Balan Ramanan",
"23/306 Tamara Brown",
"25/306 Kaia Sultana",
"26/306 Ryan Jackson",
"27/306 Anton Blomgren",
"27/306 Lomash Datta",
"01/307 Lisa Carlsen",
"07/307 Nayan Puri",
"08/307 Ayann Achari",
"10/307 Matthew Connolly",
"10/307 Tom Edwards",
"12/307 Hanima Devar",
"17/307 Ishrat Bahadur",
"17/307 Gayan Saha",
"18/307 Alice Wilson",
"21/307 Alisha Ahmad",
"21/307 Ajay Banerjee",
"22/307 David Clausen",
"24/307 Jackson Kimura",
"24/307 Gayan Tiwari",
"24/307 Saloni Gadhavi",
"24/307 Milana Tiwari",
"25/307 Nabhi Datta",
"27/307 Ladli Agarwal",
"28/307 Ronan Summers",
"28/307 Layak Mardia",
"01/308 Auguste Lund",
"01/308 Tyr Solberg",
"01/308 Sten Solberg",
"01/308 Helene Jensen",
"01/308 Gabriel Thorn",
"02/308 Nathan Wilson",
"02/308 Gandhar Sharma",
"05/308 Aahna Ramanujan",
"06/308 Shauna Suzuki",
"06/308 Shauna Jackson",
"06/308 Pascaline Legros",
"06/308 Gazala Sultana",
"09/308 Thomas Eklund",
"10/308 Rushil Sultana",
"11/308 Yui Suzuki",
"11/308 Anna Pallesen",
"12/308 Anika Bhasin",
"13/308 Teala Thorn",
"13/308 Vilina Khan",
"15/308 Desmond Sato",
"18/308 Kate Suzuki",
"19/308 Rushil Saha",
"20/308 Taylor Edwards",
"20/308 Bimala Puri",
"21/308 Suvarna Abbasi",
"21/308 Kimaya Bahadur",
"22/308 Anushka Srinivasan",
"25/308 Aahna Achari",
"26/308 Rajani Kaur",
"01/309 Felix Murphy",
"02/309 Gen Suzuki",
"02/309 Brielle Bager",
"03/309 Pranay Tiwari",
"05/309 Tuhin Puri",
"06/309 Sarah Summers",
"06/309 Ayann Chunduri",
"07/309 Chahna Asan",
"08/309 Tyr Blomgren",
"08/309 Aadesh Agarwal",
"10/309 Oviyan Gadhavi",
"11/309 Valdemar Clausen",
"11/309 Ciara Connolly",
"11/309 Mitchell Jackson",
"11/309 Flavien Monnier",
"12/309 Andrew Kimura",
"12/309 Annabelle Thorn",
"12/309 Raunak Dhar",
"12/309 Kashvi Sultana",
"16/309 Laranya Dhawan",
"17/309 Rithul Singh",
"19/309 Maalai Datta",
"20/309 Erin Morris",
"20/309 Gyan Agarwal",
"21/309 Pranay Pillai",
"22/309 Selvan Ramanujan",
"22/309 Mishka Banerjee",
"23/309 Pari Tiwari",
"24/309 Chantal Guichard",
"28/309 Ramya Dhar",
"28/309 Suvarna Bose",
"01/310 Jenya Ramanujan",
"01/310 Paavan Varadhan",
"03/310 Francois Hall",
"03/310 Felix Bager",
"04/310 Chantel Bager",
"04/310 Remy Bager",
"04/310 Lea Murphy",
"04/310 Emaan Mallick",
"04/310 Marie Murphy",
"04/310 Naadir Chandra",
"06/310 Pia Tamboli",
"09/310 Saeed Agarwal",
"10/310 Ettan Chaudhuri",
"12/310 Raunak Abbasi",
"12/310 Nira Chunduri",
"12/310 Mirai Chunduri",
"13/310 Gretel Blomgren",
"13/310 Pia Tiwari",
"14/310 Dulari Joshi",
"16/310 Gaston Carlsen",
"17/310 Gandhar Dhirwan",
"18/310 Ramya Singh",
"18/310 Chahel Asan",
"19/310 Justin Eklund",
"22/310 Bimala Lingutla",
"22/310 Rithul Maharaj",
"23/310 Noah Picard",
"23/310 Pahal Ramanan",
"23/310 Mohal Puri",
"24/310 Sten Solberg",
"25/310 Jermaine Favreau",
"25/310 Omala Banerjee",
"27/310 Avril Simon",
"27/310 Rithul Mangal",
"28/310 Justin Watanabe",
"28/310 Avni Karmarkar",
"01/311 Zahira Anand",
"01/311 Bindi Pillai",
"02/311 Torsten Solberg",
"03/311 Clara Verdier",
"03/311 Keerthana Sultana",
"04/311 Leon Thorn",
"04/311 Ravi Srinivasan",
"04/311 Nayan Khan",
"07/311 Mai Kimura",
"07/311 Chryselle Bager",
"08/311 Thevan Varma",
"09/311 Ayann Patel",
"10/311 Ettan Chunduri",
"11/311 Keya Srinivasan",
"12/311 Oviyan Shah",
"13/311 Bindi Chandra",
"14/311 Kamala Bose",
"14/311 Aadesh Ganaka",
"16/311 Remy Datta",
"17/311 Nihal Puri",
"17/311 Kaia Zaman",
"19/311 Varsha Dhar",
"20/311 Ayano Sato",
"20/311 Gayan Dhar",
"20/311 Samir Chaudhuri",
"21/311 Leif Jensen",
"21/311 Esha Devar",
"24/311 Deepa Agarwal",
"25/311 Emilie Swift",
"26/311 Ishrat Joshi",
"26/311 Thevan Gadhavi",
"26/311 Ladli Asan",
"26/311 Samir Tiwari",
"28/311 Yuval Dhirwan")
Eden_sample <- sample(Eden_birth_records,42)
print(Eden_sample)
# 23/304 Gabrielle (Chanha) Ramanan: CONSENTED (1/11)
# 02/308 Seymour (Nathan) Wilson: CONSENTED (2/11)
# 07/303 Fabrice Dupont: DEAD
# 10/307 Nicolas (Tom) Edwards: CONSENTED (3/11)
# 22/310 Rithul Maharaj: DEAD
# 16/306 Maalai Mardia: DEAD
# 04/306 Yuval Devar: DEAD
# 11/308 Anna Pallesen: DEAD
# 04/310 Marie Murphy: DEAD 
# 05/301 Nico Lund: DEAD
# 23/300 Beatrice Solberg: DEAD
# 20/309 Erin Morris: DEAD
# 11/302 Yvonne Petit: DEAD
# 07/302 Laasya Srinivasan: DEAD
# 12/307 Hanima Devar: CONSENTED (4/11)
# 26/306 Ryan Jackson: DEAD
# 13/308 Teala Thorn: DEAD
# 07/306 Emilie (Kaia) Chatterjee: CONSENTED (5/11)
# 09/304 Yuval Kulkarni: DEAD 
# 21/308 Kimaya Badahur: CONSENTED (6/11)
# 11/311 Keya Srinivasan: DEAD
# 18/304 Jacques Wilson: DEAD
# 20/308 Bimala Puri: DEAD
# 09/302 Elie Murphy: DEAD
# 17/311 Nihal Puri: DEAD
# 03/310 Felix Bager: DEAD
# 25/306 Brielle (Kaia) Sultana: CONSENTED (7/11)
# 06/309 Ayann Chunduri: CONSENTED (8/11)
# 04/310 Remy Bager: DEAD
# 27/303 Momoko Edwards: DEAD
# 27/303 Justin Herbert: DEAD
# 12/302 Beau Solberg: DEAD
# 12/304 Rushil Devar: DEAD
# 06/308 Shauna Jackson: DECLINED
# 04/301 Mizuki Edwards: DEAD
# 18/304 Kaia Ramanujan: CONSENTED (9/11)
# 04/303 Conor Wilson: DEAD
# 05/306 Elle Dupont: DEAD
# 04/311 Nayan Khan: CONSENTED (10/11)
# 25/307 Nabhi Datta: CONSENTED (11/11)
```

```{r}
set.seed(288)
#Bonne Sante Cities - Talu, Eden, Valais
Valais_birth_records <- c(
  "01/300 Riko Moore",
"04/300 Jacob Connolly",
"06/300 Emy Brown",
"06/300 Simon Sorensen",
"06/300 Olson Blomgren",
"09/300 Antoine McCarthy",
"09/300 Helga Svendsen",
"10/300 Sarah Morris",
"16/300 Mia Sato",
"17/300 Ryan Morris",
"17/300 Isobel Brown",
"18/300 Elias Solberg",
"18/300 Patricia Edwards",
"18/300 Reynard Blomgren",
"19/300 Hanna Olsen",
"19/300 Connor Murphy",
"20/300 Armand Simon",
"20/300 Paige Watanabe",
"25/300 Sarah Brown",
"26/300 Lee Brown",
"26/300 Miho Collins",
"07/301 Mike Yamada",
"07/301 Emma Blomgren",
"09/301 Tom Wilson",
"11/301 Agda Carlsen",
"11/301 Kaya Bager",
"16/301 Elsa Solberg",
"16/301 Yujia Morris",
"18/301 Akane Morris",
"21/301 Robert Moore",
"22/301 Finlay Brown",
"23/301 Lea Carlsen",
"24/301 Ai Price",
"27/301 Cariel Carlsen",
"28/301 Jakob Sorensen",
"01/302 Nanami Brown",
"01/302 Maika Solberg",
"03/302 Sophie Hall",
"05/302 Olina Eklund",
"09/302 Mike Murphy",
"10/302 Johanna Jensen",
"12/302 Lauren Sato",
"12/302 Nadege Leclerc",
"13/302 Percy Blomgren",
"13/302 Maya Sato",
"14/302 Jamie Connolly",
"14/302 Nanako Suzuki",
"14/302 Lynnea Bager",
"16/302 Martial Bouvier",
"21/302 Matthias Sorensen",
"21/302 Viktoria Sorensen",
"21/302 Gael Brun",
"27/302 Julie Lund",
"27/302 Ayaka Yamada",
"02/303 Aidan Brown",
"02/303 Ross Connolly",
"04/303 Erik Blomgren",
"06/303 Ryan Morris",
"07/303 Alina Jensen",
"09/303 Bertrand Rousseau",
"10/303 Kirstie Eklund",
"15/303 Rupert Blomgren",
"16/303 Philipp Sorensen",
"20/303 Juhani Sorensen",
"20/303 Vincent Blomgren",
"23/303 Percy Carlsen",
"23/303 Katy Coste",
"27/303 Julien Chevallier",
"28/303 Nicole Solberg",
"05/304 Neena Morris",
"09/304 Alicia Jones",
"11/304 Ole Ibsen",
"13/304 Sean Morris",
"15/304 Magalie Marin",
"18/304 Maximilian Eklund",
"24/304 Rida Jensen",
"01/305 Ryan Morris",
"01/305 Lauren Connolly",
"10/305 Nicole Solberg",
"12/305 Akane Morris",
"12/305 Robin Morris",
"15/305 Elena Sorensen",
"16/305 Antoine Solberg",
"17/305 Andre Andre",
"18/305 Halden Eklund",
"18/305 Remi Marin",
"19/305 Lionel Collin",
"24/305 Kaya Bager",
"24/305 Jeneve Bager",
"04/306 Sacha Solberg",
"10/306 Blandine Martins",
"13/306 Christele Levy",
"16/306 Laurie Jensen",
"18/306 Leah Connolly",
"21/306 Juhani Jensen",
"23/306 Brittany Moore",
"28/306 Christel Verdier",
"18/307 Leon Connolly",
"20/307 Blade Jackson",
"06/308 Djamila Marty",
"13/308 Melissa Wilson",
"05/309 Holly Connolly",
"02/311 King Wilson"
)
Valais_sample <- sample(Valais_birth_records, 45)
print(Valais_sample)
# 13/308 Melissa Wilson: DEAD
# 21/302 Viktoria Sorensen: DEAD
# 10/303 Kirstie Eklund: CONSENTED (1/11)
# 21/301 Robert Moore: DEAD
# 06/300 Emy Brown: DECLINED
# 20/300 Paige Watanabe: DEAD
# 09/300 Helga Svendsen: CONSENTED (2/11)
# 02/311 King Wilson: DEAD
# 26/300 Miho Collins: CONSENTED (3/11)
# 18/300 Patricia Edwards: DEAD
# 27/302 Renee (Ayaka) Yamada: DEAD
# 12/302 Nadege Leclerc: DEAD
# 01/305 Lauren Connolly: CONSENTED (4/11)
# 24/305 Camille (Jeneve) Bager: DECLINED 
# 10/300 Sarah Morris: DEAD
# 07/301 Mike Yamada: DECLINED
# 12/305 Akane Morris: CONSENTED (5/11)
# 01/302 Maika Solberg: DEAD
# 22/301 Finlay Brown: DEAD
# 07/301 Emma Blomgren: DEAD
# 16/303 Philipp Sorensen: DEAD
# 17/300 Isobel Brown: DEAD
# 27/303 Julien Chevallier: DEAD
# 09/304 Alicia Jones: DEAD
# 18/307 Leon Connolly: CONSENTED (6/11)
# 21/302 Matthias Sorensen: DEAD
# 02/303 Ross Connolly: DEAD
# 24/304 Rida Jensen: DECLINED
# 28/303 Nicole Solberg: DEAD
# 03/302 Sophie Hall: DEAD
# 24/305 Florence (Kaya) Bager: DECLINED
# 13/302 Percy Blomgren: DEAD
# 11/304 Ole Ibsen: CONSENTED (7/11)
# 20/303 Tristan (Juhani) Sorensen: DECLINED
# 27/302 Julie Lund: CONSENTED (8/11)
# 02/303 Aidan Brown: DECLINED
# 25/300 Sarah Brown: DEAD
# 16/301 Yujia Morris: DEAD 
# 13/306 Christele Levy: DEAD
# 19/305 Lionel Collin: DEAD
# 05/309 Holly Connolly (hell yeah): CONSENTED (9/11)
# 11/301 Agda Carlsen: CONSENTED (10/11)
# 10/302 Johanna Jensen: DEAD
# 28/301 Jakob Sorensen: DEAD
# 07/303 Juliette (Alina) Jensen: CONSENTED (11/11)

```